name: misyonbank
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  get_storage: ^2.1.1
  timezone: ^0.9.4
  logger: ^2.4.0
  info_popup: ^4.3.1
  equatable: ^2.0.5
  intl: ^0.19.0
  dio: ^5.6.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  money_input_formatter:
    git:
      url: https://github.com/HacerYaman/money-formatter
  common:
    path: module/common
  widgets:
    path: module/components
  cupertino_icons: ^1.0.8
  skeleton_text: ^3.0.1
  syncfusion_flutter_charts: ^27.1.57
  smooth_page_indicator: ^1.2.0+3
  flutter_cached_pdfview: ^0.4.2
  flutter_cache_manager: ^3.4.1
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/app_bar_icons/
    - assets/icons/nav_bar_icons/
